name: "My Container Action"
description: "A custom action that returns the answer to everything"
author: "Your Name"

inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"

outputs:
  answer:
    description: "The answer to everything"

runs:
  using: "docker"
  image: "Dockerfile"